# Generated by Django 5.2.3 on 2025-06-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
