# Generated by Django 5.2.3 on 2025-06-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uploadedpdf_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='model_name',
            field=models.CharField(choices=[('gpt-4', 'GPT-4'), ('gpt-4-turbo', 'GPT-4 Turbo')], default='gpt-4', max_length=50),
        ),
    ]
